cgkineo/adapt-quicknav

js/adapt-quicknav.js
Got parent ID of current page and navigate to that rather than trigger navigation menu button which is missing in V2 of the framework
=> Fix up button behaviour

bower.json, js/adapt-quicknav-view.js, js/adapt-quicknav.js, js/quicknav-placeholder.js
fixes #17
also a spot of refactoring partly to enable the above and partly to break the code up a bit so it's more readable
convert to AMD-style module definitions and clear up a couple of syntax things JSHint was complaining about
=> amend to get quicknav to respect the _isAvailable setting when determining next and previous pages

js/adapt-quicknav.js
=> issue-14: replace to false to preserve nav history

js/adapt-quicknav.js
=> issue-1: changed to findById

js/adapt-quicknav.js
=> issue/29: course as menu

js/adapt-quicknav.js
=> issue/31: navigate to course

js/adapt-quicknav-view.js, js/adapt-quicknav.js
=> issue/33: added _isAvailable and _isLocked support

js/model.js
=> issue/38: The component tries to reference schema attributes that dont exist

bower.json, example.json, js/model.js, js/view.js, properties.schema
#41 
* fixed example.json to match current schema and code
* added close button behaviour
=> issue/41: added close button

bower.json, js/view.js
=> issue/46: fixed classes attribute behaviour

js/view.js
=> issue/#56 Quicknav now listens for any contentObject completion event

README.md, example.json, js/model.js, properties.schema
=> Amend for #51. Added return to last location button.

js/model.js
=> Amend for closing browser functionality - #61

js/model.js
=> fixes #65 - stop load error on _previousId lookup

js/model.js
Additional fix for #49 and unstable Array sorting. Hopefully will also resolve #69.
=> Additional fix for unstable Array sorting

less/quicknav.less
#72 
* changed from display inline to display flex
=> issue/72 nvda cannot read buttons in display: inline; container

README.md, bower.json, example.json, js/adapt-quicknav.js, js/model.js, js/tooltip.js, js/view.js, properties.schema, templates/partials/quicknav-item.hbs
=> adds _lockUntilPageComplete setting

example.json, js/model.js
#80 
* Extended to siblings
* Added example json as to where the behaviour is applicable
=> issue/80 allow _lockUntilPageComplete on all buttons

less/tooltip.less
Dependant on https://github.com/adaptlearning/adapt-contrib-vanilla/pull/243
=> Border radius variable update

templates/partials/quicknav-item.hbs
https://github.com/cgkineo/adapt-quicknav/issues/85
=> Apply btn type selector dynamically
